dat<-read.table(file="f.txt", sep=",")
y<-t(dat)
a<-table(y)
a
f<-as.data.frame(a)
f[,3]<- 100*a/(sum(a))
f[,4]<- cumsum(a)
f[,5]<- cumsum(f[,3])
colnames(f)<-c("значение","частота","частость","накопленная частота","накопленная частость")
f
plot(a,type="l",main="Полигон частот",xlab="значение", ylab="частота") 
d<-as.numeric(y)
v<-sort(d)
x<-unique(v)
y<-as.numeric(f[,4])
plot(x,as.numeric(f[,4]),type="l",xlab="значение",ylab="накопленная частота", main= "Кумулята абсолютных частот")
plot(x,as.numeric(f[,5]),type="l",xlab="значение",ylab="накопленная частость", main= "Кумулята относительных частот")